In [1]:
#Erich Wang PMG SQL

In [2]:
import sqlite3
import pandas as pd

In [16]:
try:
    campaign = pd.read_csv('campaign_info.csv')
    marketing = pd.read_csv('marketing_performance.csv')
    website_revenue = pd.read_csv('website_revenue.csv')
    
    conn = sqlite3.connect('marketing_data.db')
    
    
    # SQLite
    campaign.to_sql('campaign', conn, if_exists='replace', index=False)
    marketing.to_sql('marketing_performance', conn, if_exists='replace', index=False)
    website_revenue.to_sql('website_revenue', conn, if_exists='replace', index=False)
    
    
    
    
    # Query
    query1 = "SELECT date, SUM(impressions) AS total_impressions FROM marketing_performance GROUP BY date"
    result1 = pd.read_sql_query(query1, conn)
    
    query2 = "SELECT state, SUM(revenue) AS total_revenue FROM website_revenue GROUP BY state ORDER BY total_revenue DESC LIMIT 3;"
    result2 = pd.read_sql_query(query2, conn)
    
    query3 = "SELECT m.campaign_id, SUM(cost) AS total_cost, SUM(impressions) AS total_impressions, SUM(clicks) AS total_clicks, SUM(revenue) AS total_revenue FROM marketing_performance AS m LEFT JOIN website_revenue AS w ON m.campaign_id = w.campaign_id GROUP BY m.campaign_id;"
    result3 = pd.read_sql_query(query3, conn)
    
    query4 = "SELECT wr.state, SUM(mp.conversions) AS total_conversions FROM campaign AS ci INNER JOIN marketing_performance AS mp ON ci.id = mp.campaign_id LEFT JOIN website_revenue AS wr ON ci.id = wr.campaign_id WHERE ci.name = 'Campaign5' GROUP BY wr.state ORDER BY total_conversions DESC LIMIT 1;"
    result4 = pd.read_sql_query(query4, conn)
    
    #Conversion rate
    #Click through rate
    #ROI
    
    #Conversion rate
    query5a = "SELECT mp.campaign_id, ci.name AS campaign_name, SUM(mp.conversions) AS total_conversions, SUM(mp.clicks) AS total_clicks, (SUM(mp.conversions) * 1.0 / SUM(mp.clicks)) AS conversion_rate FROM marketing_performance AS mp LEFT JOIN campaign AS ci ON mp.campaign_id = ci.id GROUP BY mp.campaign_id, ci.name ORDER BY conversion_rate DESC;"
    result5a = pd.read_sql_query(query5a, conn)
    
    #Click through rate
    query5b = "SELECT mp.campaign_id, ci.name AS campaign_name, SUM(mp.clicks) AS total_clicks, SUM(mp.impressions) AS total_impressions, SUM(mp.clicks) * 100.0 / SUM(mp.impressions) AS click_through_rate FROM marketing_performance AS mp LEFT JOIN campaign AS ci ON mp.campaign_id = ci.id GROUP BY ci.name, mp.campaign_id ORDER BY click_through_rate DESC;"
    result5b = pd.read_sql_query(query5b, conn)
    
    #ROI
    query5c = "SELECT mp.campaign_id, ci.name AS campaign_name, SUM(mp.cost) AS total_cost, SUM(wr.revenue) AS total_revenue, (SUM(wr.revenue) - SUM(mp.cost)) / SUM(mp.cost) AS roi FROM marketing_performance AS mp LEFT JOIN website_revenue AS wr ON mp.campaign_id = wr.campaign_id LEFT JOIN campaign AS ci ON mp.campaign_id = ci.id GROUP BY mp.campaign_id, ci.name ORDER BY roi DESC;"
    result5c = pd.read_sql_query(query5c, conn)

    
    # Close the connection and print output
    conn.close()
    
    print("Question 1: ")
    print(result1)

    print("Question 2: ")
    print(result2)
    
    print("Question 3: ")
    print(result3)
    
    print("Question 4: ")
    print(result4)
    
    print("Question 5: Conversion Rate")
    print(result5a)
    
    print("Question 5: Click Through Rate")
    print(result5b)
    
    print("Question 5: ROI")
    print(result5c)
    
    
except Exception as e:
    print("Error:", str(e))

Question 1:
                  date  total_impressions
0   2023-07-24 0:00:00               1423
1   2023-07-26 0:00:00               1547
2   2023-07-27 0:00:00               2295
3   2023-07-28 0:00:00               8142
4   2023-07-29 0:00:00               3511
5   2023-07-30 0:00:00               3001
6   2023-08-02 0:00:00               1532
7   2023-08-03 0:00:00               3189
8   2023-08-04 0:00:00               3254
9   2023-08-05 0:00:00               1088
10  2023-08-10 0:00:00               2128
11  2023-08-11 0:00:00               2278
12  2023-08-12 0:00:00               6588
13  2023-08-13 0:00:00               2170
14  2023-08-14 0:00:00               5773
15  2023-08-17 0:00:00               3292
16  2023-08-19 0:00:00               1248
Question 2:
  state  total_revenue
0    NY          46398
1    GA          39666
2    OH          37577
Question 3:
   campaign_id  total_cost  total_impressions  total_clicks  total_revenue
0     55304737     4075.50              40938         29652         155308
1     64441550     4170.51              42810         38724         151792
2     86363015     3970.14              47508         33318         163396
3     89363211    15809.04             158280        116048         551672
4     99058240     4077.15              25641         33663         136404
Question 4:
  state  total_conversions
0    GA               3342
Question 5: Conversion Rate
   campaign_id campaign_name  total_conversions  total_clicks  conversion_rate
0     89363211     Campaign3               4451         14506         0.306839
1     55304737     Campaign2               1516          4942         0.306758
2     86363015     Campaign4               1551          5553         0.279308
3     64441550     Campaign1               3018         12908         0.233808
4     99058240     Campaign5               1114          4809         0.231649
Question 5: Click Through Rate
   campaign_id campaign_name  total_clicks  total_impressions  \
0     99058240     Campaign5          4809               3663
1     64441550     Campaign1         12908              14270
2     89363211     Campaign3         14506              19785
3     55304737     Campaign2          4942               6823
4     86363015     Campaign4          5553               7918

   click_through_rate
0          131.285831
1           90.455501
2           73.318170
3           72.431482
4           70.131346
Question 5: ROI
   campaign_id campaign_name  total_cost  total_revenue        roi
0     86363015     Campaign4     3970.14         163396  40.156231
1     55304737     Campaign2     4075.50         155308  37.107717
2     64441550     Campaign1     4170.51         151792  35.396508
3     89363211     Campaign3    15809.04         551672  33.895984
4     99058240     Campaign5     4077.15         136404  32.455723

In [ ]:
#Problem 2: 3rd best state Ohio generated 37577 total revenue.

In [ ]:
#Problem 5: Conversion rate, click through rate, and ROI were calcuated above to assess efficiency of different campaigns
# Conversion rate woud be useful to assess desired actions taken
# Click through rate would be good for assessing awareness
# ROI would be useful to measure financial health of campaign
# Thus, depending on what the marketing professional wants, different measures of efficiency would be assessed

# Campaign 3 has highest conversion rate when compared to other campaigns
# Campaign 5 has highest click through rate when compared to other campaigns
# Campaign 4 has highest ROI when compared to other campaigns